import assert from 'node:assert/strict'
import fs from 'node:fs'
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {})})
const page=await browser.newPage({viewport:{width:1440,height:1000}})
const errors=[]; page.on('pageerror',e=>errors.push(e.message))
const base=process.env.HARNESS_URL || 'http://127.0.0.1:5199'
const calls=()=>page.evaluate(()=>window.__beta5Calls)
try {
  await page.goto(`${base}/harness/beta5.html?scenario=project-denied`)
  await page.getByLabel('Demo repository',{exact:true}).selectOption('fixture/demo')
  await page.getByRole('alert').getByText(/Projects permission denied/).waitFor()
  await page.getByRole('button',{name:'Connect product',exact:true}).click()
  await page.getByRole('status').getByText(/Connected/).waitFor()
  assert.equal((await calls())[0].args.projectUrl,'')
  await page.goto(`${base}/harness/beta5.html`)
  await page.getByText('Create a repository',{exact:true}).click()
  await page.getByRole('button',{name:'Create private repository',exact:true}).click()
  await page.getByRole('status').getByText(/Created fixture\/demo/).waitFor()
  await page.getByText('Create a Project',{exact:true}).click()
  await page.getByRole('button',{name:'Create GitHub Project',exact:true}).click()
  await page.getByRole('status').getByText(/Project write permission denied/).waitFor()
  assert.equal(await page.getByLabel('Demo repository',{exact:true}).inputValue(),'fixture/demo')
  await page.getByLabel('Demo project',{exact:true}).selectOption('https://github.com/users/fixture/projects/1')
  await page.getByRole('button',{name:'Connect product',exact:true}).click()
  await page.getByRole('status').getByText(/Connected/).waitFor()
  assert.equal((await calls()).filter(c=>c.command==='create-repo').length,1)
  assert.equal((await calls()).find(c=>c.command==='connect-product').args.projectUrl,'https://github.com/users/fixture/projects/1')
  console.log('PASS: repo-only setup, Project permission error and partial creation recovery')
  await page.goto(`${base}/harness/beta5.html?scenario=model-failed`)
  await page.getByRole('button',{name:'Verify & use as default',exact:true}).click()
  await page.getByRole('status').getByText(/Fixture verification failed/).waitFor()
  assert.equal((await calls()).length,0)
  await page.goto(`${base}/harness/beta5.html?scenario=model-ok`)
  await page.getByRole('button',{name:'Verify & use as default',exact:true}).click()
  await page.getByRole('status').getByText(/Verified and saved/).waitFor()
  assert.equal((await calls())[0].command,'default-provider')
  console.log('PASS: failed model verification never saves the default')
  await page.goto(`${base}/harness/beta5.html?scenario=agents`)
  await page.getByRole('heading',{name:'Agents',exact:true}).waitFor()
  await page.getByRole('cell',{name:'QA agent QA',exact:true}).waitFor()
  await page.getByLabel('Role filter').selectOption('manager')
  assert.equal(await page.getByRole('cell',{name:'QA agent QA',exact:true}).count(),0)
  await page.getByRole('button',{name:'Add agent',exact:true}).click()
  await page.getByLabel('Role',{exact:true}).selectOption('manager')
  await page.getByLabel('Space',{exact:true}).selectOption('103')
  await page.getByLabel('Name',{exact:true}).fill('Demo manager')
  await page.getByRole('button',{name:'Create manager',exact:true}).click()
  await page.getByRole('heading',{name:'Demo manager',exact:true}).waitFor()
  assert.equal((await calls()).filter(c=>c.command==='create-manager').length,1)
  await page.getByRole('button',{name:'Add agent',exact:true}).click()
  await page.getByLabel('Role',{exact:true}).selectOption('worker')
  await page.getByLabel('Role profile',{exact:true}).selectOption('Developer')
  await page.getByLabel('Space',{exact:true}).selectOption('103')
  await page.getByRole('button',{name:'Continue',exact:true}).click()
  await page.getByPlaceholder('Scribe',{exact:true}).fill('Demo developer')
  await page.getByRole('button',{name:'Make it',exact:true}).click()
  await page.getByLabel('Role filter').selectOption('worker')
  await page.getByRole('cell',{name:'Demo developer Developer',exact:true}).waitFor()
  const saved=(await calls()).find(c=>c.command==='save-worker').args.worker
  assert.equal(saved.category,'worker'); assert.equal(saved.profile,'Developer'); assert.deepEqual(saved.spaces,[103])
  fs.mkdirSync('docs/screenshots/beta5',{recursive:true})
  await page.getByLabel('Role filter').selectOption('all')
  await page.screenshot({path:'docs/screenshots/beta5/agents.png'})
  console.log('PASS: unified list, role filter and manager/worker creation with role profile and space')
  assert.deepEqual(errors,[])
} finally {await browser.close()}
